### ISSUE TITLE
Cómo encontrar las diapos del workshop?

### ISSUE THREAD

**Issue by iremendoza** [ecoinfAEET/rmarkdown_tutorial#1]
Hola!

En el repositorio de Rmarkdown, sólo estoy viendo el archivo Readme... Cómo puedo bajarme las diapos del workshop?

**Comment by ajpelu** [comment]
@iremendoza creo que es este [enlace](https://t.co/QhFluBlSgW). Lo saqué de este [tweet](https://twitter.com/frod_san/status/827838962362351616) de @pakillo. 
@Pakillo podrías ponerlo en el Repo? Gracias.

**Comment by Pakillo** [comment]
Done! Perdón por el delay... Enjoy!
